### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by mxdavis** [learn-co-curriculum/react-presentation-components#9]
Failed to compile
TypeError: Cannot read property 'request' of undefined
  
  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [react-presentation-components-lab-v-000]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
  
  - ExternalModuleFactoryPlugin.js:46 next
    [react-presentation-components-lab-v-000]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
  
  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [react-presentation-components-lab-v-000]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
  
  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [react-presentation-components-lab-v-000]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
  
  - NormalModuleFactory.js:246 applyPluginsAsyncWaterfall
    [react-presentation-components-lab-v-000]/[react-scripts]/[webpack]/lib/NormalModuleFactory.js:246:4
  
  - Tapable.js:204 
    [react-presentation-components-lab-v-000]/[tapable]/lib/Tapable.js:204:11
  
  - IgnorePlugin.js:56 IgnorePlugin.checkIgnore
    [react-presentation-components-lab-v-000]/[react-scripts]/[webpack]/lib/IgnorePlugin.js:56:10
  
  - Tapable.js:208 NormalModuleFactory.applyPluginsAsyncWaterfall
    [react-presentation-components-lab-v-000]/[tapable]/lib/Tapable.js:208:13
  
  - NormalModuleFactory.js:230 NormalModuleFactory.create
    [react-presentation-components-lab-v-000]/[react-scripts]/[webpack]/lib/NormalModuleFactory.js:230:8
  
  - Compilation.js:382 Compilation._addModuleChain
    [react-presentation-components-lab-v-000]/[react-scripts]/[webpack]/lib/Compilation.js:382:17
  
  - Compilation.js:464 Compilation.addEntry
    [react-presentation-components-lab-v-000]/[react-scripts]/[webpack]/lib/Compilation.js:464:8
  
  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [react-presentation-components-lab-v-000]/[webpack]/lib/SingleEntryPlugin.js:22:15
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [react-presentation-components-lab-v-000]/[tapable]/lib/Tapable.js:229:14
  
  - Compiler.js:488 
    [react-presentation-components-lab-v-000]/[react-scripts]/[webpack]/lib/Compiler.js:488:8
  
  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [react-presentation-components-lab-v-000]/[tapable]/lib/Tapable.js:131:46
  
  - Compiler.js:481 Compiler.compile
    [react-presentation-components-lab-v-000]/[react-scripts]/[webpack]/lib/Compiler.js:481:7

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
